services:
  rest:
    build:
      context: .
      dockerfile: etc/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: python -m uvicorn main:app --host 0.0.0.0 --port 9000 --reload

  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

    image: postgres:15-alpine
    volumes:
      - db:/var/lib/postgresql/data
      - ./etc/init.db:/docker-entrypoint-initdb.d/init.sql:rw
    restart: always
    env_file:
      - .env

volumes:
  db:
