# Generated by Django 3.2 on 2022-04-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_counter',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
