# Generated by Django 3.2 on 2022-04-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_update_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
